repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.0
    hooks:
      - id: clang-format
        name: Formating C files with Clang-Format
        files: \.(c|cc|cpp|cxx|h|hh|hpp)$
        args: ["-style=file"]
default_stages: [pre-commit]
exclude: ^(vendor|build|dist|node_modules|\.git)/
